# -*- coding: utf-8 -*-
"""
    consts.py

    :copyright (C) 2020  Jaeho
    :license: GPL-3.0
"""
# Scale factors
SCALE_FOR_SPATIAL_VARIABLES_Z: float = 1e-2
SCALE_FOR_PRESSURE: float = 1e6
SCALE_FOR_TEMPORAL_VARIABLE: float = 1e-6

# Material parameter IDs
WAVE_SPEED_PARAM_ID: int = 1
MASS_DENSITY_PARAM_ID: int = 2
NON_LINEARITY_COEFFICIENT_PARAM_ID: int = 3
CONSTANT_OF_ATTENUATION_PARAM_ID: int = 4
EXPONENT_OF_ATTENUATION_PARAM_ID: int = 5

# History types
NO_HISTORY: int = 0
POSITION_HISTORY: int = 1
PROFILE_HISTORY: int = 2
FULL_HISTORY: int = 3
PLANE_HISTORY: int = 4
PLANE_BY_CHANNEL_HISTORY: int = 5

# Aberration types
NO_ABERRATION_AND_HOMOGENEOUS_MEDIUM: int = 0
ABERRATION_FROM_DELAY_SCREEN_BODY_WALL: int = 1
ABERRATION_FROM_FILE: int = 2
ABERRATION_PHANTOM: int = 3
